fix dtbo
Signed-off-by: Rancemxn <209220634+Rancemxn@users.noreply.github.com>

diff --git a/.github/workflows/build_kernel.yml b/.github/workflows/build_kernel.yml
--- a/.github/workflows/build_kernel.yml
+++ b/.github/workflows/build_kernel.yml
@@ -115,23 +115,26 @@ jobs:
       - name: Generate dtbo
         run: |
           cd ${{ env.OPPO_K10X_RootPath }}/kernel/msm-5.4/out/arch/arm64/boot
-          curl -fL "https://android.googlesource.com/platform/system/libufdt/+archive/refs/heads/main/utils/src.tar.gz" -o libufdt.tar.gz --connect-timeout 30 --retry 5 --retry-delay 5
-          mkdir -p libufdt
-          tar -xzf libufdt.tar.gz -C libufdt
-          rm libufdt.tar.gz
-          DTBO_LIST=$(find dts/vendor -name "*.dtbo")
-    
-          if echo "$DTBO_LIST" | grep -q "oscar"; then
-              echo "Found OPPO Oscar specific DTBOs, proceed to pack..."
-          else
-              echo "Warning: Oscar DTBOs not found! Your touch might still lag."
+          
+          curl -fL "https://android.googlesource.com/platform/system/libufdt/+archive/refs/heads/main/utils/src.tar.gz" -o libufdt.tar.gz
+          mkdir -p libufdt && tar -xzf libufdt.tar.gz -C libufdt
+          
+          TARGET_DTBO=$(find dts/vendor -name "*-216EA-overlay.dtbo" | head -n 1)
+          
+          if [ -z "$TARGET_DTBO" ]; then
+              echo "Error: holi-oscar-216EA-overlay.dtbo not found!"
+              exit 1
           fi
+          echo "Target DTBO found for Oscar 216EA: $TARGET_DTBO"
           
-          echo "Files being packed into dtbo.img:"
-          echo "$DTBO_LIST"
+          mkdir -p padding_dtbos
+          for i in $(seq -f "%02g" 0 63); do
+              cp "$TARGET_DTBO" "padding_dtbos/pad_${i}.dtbo"
+          done
           
-          python3 libufdt/mkdtboimg.py create dtbo.img --page_size=4096 --version=0 $DTBO_LIST
+          python3 libufdt/mkdtboimg.py create dtbo.img --page_size=4096 --version=0 padding_dtbos/*.dtbo
           
+          echo "Success: dtbo.img has been created with 64 identical slots of 216EA."
           ls -lh dtbo.img
 
       - name: Upload DTBO/DTB Files
